### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by NDurham12** [ysmood/notell#2]
Hi, 

I'm trying to use your code for a reveal presentation and am unable to install per the readme instructions.  

![image](https://cloud.githubusercontent.com/assets/5875789/6456464/b267b168-c129-11e4-87c3-7808126b97eb.png)

Log Details: 

0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'setup' ]
2 info using npm@2.4.1
3 info using node@v0.12.0
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info presetup notell@0.0.1
6 info setup notell@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info notell@0.0.1 Failed to exec setup script
9 verbose stack Error: notell@0.0.1 setup: `kit/app_mgr.sh setup`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1008:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10 verbose pkgid notell@0.0.1
11 verbose cwd D:\Repositories\gdiHouston\notell
12 error Windows_NT 6.3.9600
13 error argv "node" "C:\\Users\\XXX\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "setup"
14 error node v0.12.0
15 error npm  v2.4.1
16 error code ELIFECYCLE
17 error notell@0.0.1 setup: `kit/app_mgr.sh setup`
17 error Exit status 1
18 error Failed at the notell@0.0.1 setup script 'kit/app_mgr.sh setup'.
18 error This is most likely a problem with the notell package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     kit/app_mgr.sh setup
18 error You can get their info via:
18 error     npm owner ls notell
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by ysmood** [comment]
Sorry, I only test it on Mac and Linux, shell does works for Windows.
I have planed to refactor the project to support all major systems, but for now, I just don't have spare time.

**Comment by ysmood** [comment]
Fixed

**Comment by ysmood** [comment]
@NDurham12 Fixed, please try again.

**Comment by NDurham12** [comment]
Oh great! I'll try again tonight
