### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by andrewwiik** [ysmood/notell#3]
Can you use this on github pages or no?

**Comment by ysmood** [comment]
No, but it would be fun to implement it. If we use the Webrtc, it is possible to do so, but now it needs a server to exchange data between browsers.

**Comment by andrewwiik** [comment]
could you help me maybe implement it, and the nwe can add the feature to project after we know it's working

**Comment by ysmood** [comment]
If I have time, I will try it. But I have a lot of work waiting for me to finish.

**Comment by jramscr** [comment]
Hi! I just read these comments but I have a question. Does this works on heroku servers or similar?

**Comment by ysmood** [comment]
@jramscr Yes, I should work without problem on heroku.

**Comment by jramscr** [comment]
Oh right! Thanks! I'm going to implemented it, and try to make a short tutorial in order to make it useful!
