### ISSUE TITLE
Add content from page subfolders?

### ISSUE THREAD

**Issue by x421** [ysmood/notell#4]
Hi there,

I have an old presentation which uses subfolders with content, where do I have to put it so notell will see it? I named the ejs file "his_db" and it gets recognized, I then tried subfolders in the root and usr/ with the same name and content inside of it.

The error(s):

```
>> 404: /his_db/css/reveal.css
>> 404: /his_db/lib/css/zenburn.css
>> 404: /his_db/lib/js/head.min.js
>> 404: /his_db/js/reveal.js
>> 404: /his_db/app/js/guest.js
>> 404: /his_db/app/js/host.js
>> 404: /his_db/app/js/notell.js
>> 404: /his_db/css/print/paper.css
```

**Comment by ysmood** [comment]
You have to put it with your project name, such as `usr/my_ppt/his_db `, not `usr/his_db`

**Comment by x421** [comment]
Thank you very much!
